package httpClientTest;

import java.io.DataOutputStream;
import java.io.IOException;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.HashMap;
import java.util.Map;

public class Entrance {

	public static void main(String[] args) {
		
		System.out.println("Hello World!");
	}

	public void httpGet() throws IOException {
		Map<String, String> params = new HashMap<>();
		params.put("Authorization", "eyJhbGciOiJQUzI1NiJ9.eyJpc3MiOiJhcGktZGVtby5zdGFybGluZ2JhbmsuY29tIiwic3ViIjoiNTdlNTBjZWMtZWY0Yi00ZjczLWJkMjItZDFjZDQxZTQwMDYzIiwiZXhwIjoxNTY5OTM0MzM0LCJpYXQiOjE1Njk4NDc5MzQsInNjb3BlIjoiYWNjb3VudC1ob2xkZXItbmFtZTpyZWFkIGFjY291bnQtaG9sZGVyLXR5cGU6cmVhZCBhY2NvdW50LWlkZW50aWZpZXI6cmVhZCBhY2NvdW50LWxpc3Q6cmVhZCBhY2NvdW50OnJlYWQgYWRkcmVzczplZGl0IGFkZHJlc3M6cmVhZCBhdHRhY2htZW50OnJlYWQgYXV0aG9yaXNpbmctaW5kaXZpZHVhbDpyZWFkIGJhbGFuY2U6cmVhZCBjYXJkLWNvbnRyb2w6ZWRpdCBjYXJkOnJlYWQgY29uZmlybWF0aW9uLW9mLWZ1bmRzOnJlYWQgY3VzdG9tZXI6cmVhZCBlbWFpbDplZGl0IG1hbmRhdGU6ZGVsZXRlIG1hbmRhdGU6cmVhZCBtZXJjaGFudDpyZWFkIG1ldGFkYXRhOmNyZWF0ZSBtZXRhZGF0YTplZGl0IHBheWVlOmNyZWF0ZSBwYXllZTpkZWxldGUgcGF5ZWU6ZWRpdCBwYXllZS1pbWFnZTpyZWFkIHBheWVlOnJlYWQgcGF5LWZvcmVpZ246Y3JlYXRlIHBheS1sb2NhbDpjcmVhdGUgcGF5LWxvY2FsLW9uY2U6Y3JlYXRlIHBheS1sb2NhbDpyZWFkIHJlY2VpcHQ6cmVhZCByZWNlaXB0czpyZWFkIHJlY2VpcHQ6d3JpdGUgc2F2aW5ncy1nb2FsOmNyZWF0ZSBzYXZpbmdzLWdvYWw6ZGVsZXRlIHNhdmluZ3MtZ29hbDpyZWFkIHNhdmluZ3MtZ29hbC10cmFuc2ZlcjpjcmVhdGUgc2F2aW5ncy1nb2FsLXRyYW5zZmVyOmRlbGV0ZSBzYXZpbmdzLWdvYWwtdHJhbnNmZXI6cmVhZCBzdGFuZGluZy1vcmRlcjpjcmVhdGUgc3RhbmRpbmctb3JkZXI6ZGVsZXRlIHN0YW5kaW5nLW9yZGVyOnJlYWQgc3RhdGVtZW50LWNzdjpyZWFkIHN0YXRlbWVudC1wZGY6cmVhZCB0cmFuc2FjdGlvbjplZGl0IHRyYW5zYWN0aW9uOnJlYWQiLCJhY2NvdW50SG9sZGVyVWlkIjoiODUwZWIwMDAtOGRiMy00OGQ2LTlkZmMtMjRkOTk1OTNhMGRkIiwidG9rZW5VaWQiOiIzYmE0M2M2Ny0xODViLTRkZWItYmM1ZS02NTA2Yzc5MmZiZWMiLCJhcGlBY2Nlc3NVaWQiOiI4ZDU2ZGJlMS0xOTU5LTQwYzYtYWJjMi01YmFjZGEzNWIzZDAifQ.fCzNCV6lNSXeXnSxEbrnAAkEr6s3BPf_98-PEzfX4U7N6cwR1r-bgQRyTOlGjRRjDYebExgirBeKlSNtXQpV07qZkbdbTC2BrKhGMkjsvTDypNQ2TNRzE1UAFNVAnpFH-NskdjAxEC3vOkMcDMnoDDsNRtUd6FQ6pDHfrnlQ0rCA9reiCpTIGxQ4c9raJNR4j0sOFZ4u8XkIQDeDAyo5Jclrg_hZ1-8vYG0Yn0yHYBLEEZ3y5fKrFZc1ytC6Pods-62CTdc2yOLI2FEc-WHxFshqJDneZc98j-HZLVO9cRwefYizcyVirc0E6VKeSm2T-Gn7FaypdHsQd74sL2wp3EmXJfGCBQ_XyAZjNuMEzm71klWJKp-yja0YMCaUYYh05pKL9vlYqSs2fZhZeBLPh5fCOGC_sDSogdPJRjfIjyvdh6E6TmDBFn7G8FOLdlyvxS0PRcTg2QWmrl5cOhsxhmi0-VJG7w0FDzhgREOT_i-67HMp6yIJepMUzrrmOTCEQ2RAms1mxIuc9ZZyeI25umPIPBs7-ix1dG3Q4trWSzGjUqt3iRqHSAOsbPAbDbbm0Kruj9efvE6KiI1CLE5hFj1EDtmCSu6tMkz0hB5YiZw1IipZtE3L-59ZMiTrt37IM_brtiocPKL4ZS6coFFfsdKxcgexDBrBrKcQNdh5clc");
		params.put("User-Agent", "Linda Lau");
		URL url = new URL("https://api-sandbox.starlingbank.com");
		
		HttpURLConnection connection = (HttpURLConnection) url.openConnection();
		connection.setRequestMethod("GET");
		connection.setDoOutput(true);
		
		DataOutputStream output = new DataOutputStream(connection.getOutputStream());
		output.flush();
		output.close();
	}
	
	
}
